using UWRandomizerEditor.LEV.Blocks;
using UWRandomizerEditor.LEV.GameObjects.Specifics;

namespace UWRandomizerEditor.LEV.GameObjects;

/// <summary>
/// This class controls the creation of game objects based upon their id and a large reference table.
/// </summary>
public static class GameObjectFactory
{
    // ReSharper disable once CognitiveComplexity
    /// <summary>
    /// This creates a <see cref="GameObject"/> based on the provided buffer and its index in the array.
    /// Static or Mobile objects are created based on the itemID, index and buffer length.
    /// </summary>
    /// <param name="buffer">byte buffer containing the data. ItemID is extracted from this</param>
    /// <param name="idxAtArray">index at array to pass along to the object and double-check if the buffer length is adequate</param>
    /// <returns>
    ///   A GameObject that can be cast to the appropriate type later. Some will have the flag 'Invalid',
    ///   which means they have some combination of ItemID and idxAtArray and Buffer length that shouldn't happen, but
    ///   does happen.
    /// </returns>
    /// <exception cref="InvalidOperationException">Thrown if the buffer length is inadequate (different from
    /// <see cref="GameObject.FixedBufferLength"/> or <see cref="MobileObject.FixedMobileBufferLength"/>) </exception>
    /// <exception cref="Exception">Thrown when the itemID can't be matched to an existing object (greater than 0x1ff)</exception>
    public static GameObject CreateFromBuffer(byte[] buffer, ushort idxAtArray)
    {
        // Next refactor:
        // Accept a dict which correlated the object ID and its corresponding object type to be created.
        // Use Activator.CreateInstance(dict[id], buffer, idxAtArray) to instantiate the object
        // Add it to the AllGameObjects array
        
        if ((idxAtArray == 0) | (idxAtArray == 1)) // These never hold actual object data.
        {
            return new MobileObject(buffer, idxAtArray);
        }

        // Create a StaticObject just to get the ItemID for later.
        var tempObject = new StaticObject(buffer[0..8], 2);
        var itemID = tempObject.ItemID;

        // Start is always MobileObjects
        if (idxAtArray < MapObjBlock.NumOfMobileObjects)
        {
            if (buffer.Length != MobileObject.FixedMobileBufferLength)
            {
                throw new InvalidOperationException(
                    $"Cannot create a Mobile Object with buffer of length {buffer.Length}");
            }

            // Mobile objects can only have itemIDs in this range
            if ((itemID >= 0x40) & (itemID <= 0x7f))
            {
                return new MobileObject(buffer, idxAtArray);
            }

            // Outside this range, it's not a valid MobileObject
            return new MobileObject(buffer, idxAtArray);
        }

        // Rest is always StaticObjects
        if (idxAtArray < (MapObjBlock.NumOfMobileObjects + MapObjBlock.NumOfStaticObjects))
        {
            // ReSharper disable once AccessToStaticMemberViaDerivedType
            if (buffer.Length != StaticObject.FixedBufferLength)
            {
                throw new InvalidOperationException(
                    $"Cannot create a Static Object with buffer of length {buffer.Length}");
            }

            if (itemID <= 0x1f) // Weapons and missiles
                return new StaticObject(buffer, idxAtArray);
            if (itemID >= 0x20 & itemID <= 0x3f) // Armor and clothes
                return new StaticObject(buffer, idxAtArray);
            // Monsters -- dealt above. Always MobileObject. If it's here, it's invalid
            if (itemID >= 0x40 & itemID <= 0x7f)
                return new StaticObject(buffer, idxAtArray);
            if (itemID >= 0x80 & itemID <= 0x8f) // Containers
                return new Container(buffer, idxAtArray);
            if (itemID >= 0x90 & itemID <= 0x97) // Light sources
                return new StaticObject(buffer, idxAtArray);
            if (itemID >= 0x98 & itemID <= 0x9f) // Wands
                return new StaticObject(buffer, idxAtArray);
            if (itemID >= 0xa0 & itemID <= 0xaf) // Treasure
                return new StaticObject(buffer, idxAtArray);
            if (itemID >= 0xb0 & itemID <= 0xbf) // Comestible
                return new StaticObject(buffer, idxAtArray);
            if (itemID >= 0xc0 & itemID <= 0xdf) // Scenery and junk
                return new StaticObject(buffer, idxAtArray);
            if (itemID >= 0xe0 & itemID <= 0xff) // Runes and bits of key
                return new StaticObject(buffer, idxAtArray);
            if (itemID >= 0x100 & itemID <= 0x10e)
                return new Key(buffer, idxAtArray);
            if (itemID == 0x10f)
                return new Lock(buffer, idxAtArray);
            if (itemID >= 0x110 & itemID <= 0x11f) // quest items
                return new StaticObject(buffer, idxAtArray);
            if (itemID >= 0x120 & itemID <= 0x12f) // Inventory items, misc stuff
                return new StaticObject(buffer, idxAtArray);
            if (itemID >= 0x130 & itemID <= 0x13f) // Books and scrolls
                return new StaticObject(buffer, idxAtArray);
            if (itemID >= 0x140 & itemID <= 0x14f) // Doors
                return new Door(buffer, idxAtArray);
            if (itemID >= 0x150 & itemID <= 0x15f) // Furniture
                return new Furniture(buffer, idxAtArray);
            if (itemID >= 0x160 & itemID <= 0x16f) // Pillars, etc
                return new Furniture(buffer, idxAtArray); // TODO: should be joined with furniture?
            if (itemID >= 0x170 & itemID <= 0x17f) // Switches
                return new TexturedGameObject(buffer, idxAtArray);
            if (itemID >= 0x180 & itemID <= 0x19f) // Traps
                return new Trap(buffer, idxAtArray);
            if (itemID >= 0x1a0 & itemID <= 0x1bf) // Triggers
                return new Trigger(buffer, idxAtArray);
            if (itemID >= 0x1c0 & itemID <= 0x1cf) // Explosions, splats, fountain, silver tree
                return new StaticObject(buffer, idxAtArray);
            if (itemID > 0x1cf & itemID <= 0x1ff) // Not described in the text
                return new StaticObject(buffer, idxAtArray);

            throw new Exception($"Can't create object with itemID {itemID}");
        }


        throw new InvalidOperationException(
            $"Object could not be created. Either invalid buffer length ({buffer.Length}) or invalid index {idxAtArray} in GameObjectFactory");
    }
}

public static class UW1ObjectHC
{
// Lifted straight from UWE
    public enum UW1GameObjectType
    {
        Null,
        Weapon,
        Melee,
        Ranged,
        SpecialRanged,
        Projectile,
        SpecialProjectile,
        Armour,
        Baubles,
        SpecialBauble,
        Shield,
        SpecialShield,
        Monster,
        Container,
        Light,
        Wand,
        Gold,
        Treasure,
        Food,
        Drink,
        Potion,
        Grass,
        Bones,
        Runestone,
        Key,
        Lock,
        DoorTrap,
        Book,
        Spell,
        Scroll,
        Map,
        Door,
        DialLever,
        Model,
        ContainerModel,
        Grave,
        VerticalTexture,
        MapObject,
        Lever,
        Writing,
        Trap,
        Trigger,
        Animated,
        Effect,
        Unpickable,
        Uncountable,
        Countable,
        CeilingHugger,
        Unknown
    }

    public static readonly Dictionary<ushort, UW1GameObjectType> UW1ObjectTypes =
        new Dictionary<ushort, UW1GameObjectType>()
        {
            { 0, UW1GameObjectType.Melee }, //"Hand axe"
            { 1, UW1GameObjectType.Melee }, //"Battle axe";
            { 2, UW1GameObjectType.Melee }, //"Axe";
            { 3, UW1GameObjectType.Melee }, //"Dagger"},
            { 4, UW1GameObjectType.Melee }, //"Shortsword"},
            { 5, UW1GameObjectType.Melee }, //"Longsword"},
            { 6, UW1GameObjectType.Melee }, //"Broadsword"},
            { 7, UW1GameObjectType.Melee }, //"Cudgel"},
            { 8, UW1GameObjectType.Melee }, //"Light mace"},
            { 9, UW1GameObjectType.Melee }, //"Mace"},
            { 10, UW1GameObjectType.Melee }, //"Shiny sword"},
            { 11, UW1GameObjectType.Melee }, //"Jeweled axe"},
            { 12, UW1GameObjectType.Melee }, //"Black sword"},
            { 13, UW1GameObjectType.Melee }, //"Jeweled sword"},
            { 14, UW1GameObjectType.Melee }, //"Jeweled mace"},
            { 15, UW1GameObjectType.Unknown }, //"Fist"},
            { 16, UW1GameObjectType.Projectile }, //"Sling stone"},
            { 17, UW1GameObjectType.Projectile }, //"Crossbow bolt"},
            { 18, UW1GameObjectType.Projectile }, //"Arrow"},
            { 19, UW1GameObjectType.SpecialProjectile }, //"Stone"},
            { 20, UW1GameObjectType.SpecialProjectile }, //"Fireball"},
            { 21, UW1GameObjectType.SpecialProjectile }, //"Lightning bolt"},
            { 22, UW1GameObjectType.SpecialProjectile }, //"Acid"},
            { 23, UW1GameObjectType.SpecialProjectile }, //"Magic missile"},
            { 24, UW1GameObjectType.Ranged }, //"Sling"},
            { 25, UW1GameObjectType.Ranged }, //"Bow"},
            { 26, UW1GameObjectType.Ranged }, //"Crossbow"},
            { 27, UW1GameObjectType.SpecialRanged }, //"Unknown"},
            { 28, UW1GameObjectType.SpecialRanged }, //"Unknown"},
            { 29, UW1GameObjectType.SpecialRanged }, //"Unknown"},
            { 30, UW1GameObjectType.SpecialRanged }, //"Unknown"},
            { 31, UW1GameObjectType.Ranged }, //"Jeweled bow"},
            { 32, UW1GameObjectType.Armour }, // "Leather vest"},
            { 33, UW1GameObjectType.Armour }, //"Mail shirt"},
            { 34, UW1GameObjectType.Armour }, //"Breastplate"},
            { 35, UW1GameObjectType.Armour }, //"Leather leggings"},
            { 36, UW1GameObjectType.Armour }, //"Mail leggings"},
            { 37, UW1GameObjectType.Armour }, //"Plate leggings"},
            { 38, UW1GameObjectType.Armour }, //"Leather gloves"},
            { 39, UW1GameObjectType.Armour }, //"Chain gauntlets"},
            { 40, UW1GameObjectType.Armour }, //"Plate gauntlets"},
            { 41, UW1GameObjectType.Armour }, //"Leather boots"},
            { 42, UW1GameObjectType.Armour }, //"Chain boots"},
            { 43, UW1GameObjectType.Armour }, //"Plate boots"},
            { 44, UW1GameObjectType.Armour }, //"Leather cap"},
            { 45, UW1GameObjectType.Armour }, //"Chain cowl"},
            { 46, UW1GameObjectType.Armour }, //"Helmet"},
            { 47, UW1GameObjectType.Armour }, //"Dragon skin boots"},
            { 48, UW1GameObjectType.Baubles }, //"Crown"},
            { 49, UW1GameObjectType.Baubles }, //"Crown"},
            { 50, UW1GameObjectType.Baubles }, //"Crown"},
            { 51, UW1GameObjectType.SpecialBauble }, //"Unknown ring 1"},
            { 52, UW1GameObjectType.SpecialBauble }, //"Unknown ring 2"},
            { 53, UW1GameObjectType.SpecialBauble }, //"Unknown ring 3"},
            { 54, UW1GameObjectType.Baubles }, //"Iron ring"},
            { 55, UW1GameObjectType.Shield }, //"Shiny shield"},
            { 56, UW1GameObjectType.Baubles }, //"Gold ring"},
            { 57, UW1GameObjectType.Baubles }, //"Silver ring"},
            { 58, UW1GameObjectType.Baubles }, //"Red ring"},
            { 59, UW1GameObjectType.Shield }, //"Tower shield"},
            { 60, UW1GameObjectType.Shield }, //"Wooden shield"},
            { 61, UW1GameObjectType.Shield }, //"Small shield"},
            { 62, UW1GameObjectType.Shield }, //"Buckler"},
            { 63, UW1GameObjectType.Shield }, //"Jeweled shield"},
            { 64, UW1GameObjectType.Monster }, //"Rotworm"},
            { 65, UW1GameObjectType.Monster }, //"Flesh slug"},
            { 66, UW1GameObjectType.Monster }, //"Cave bat"},
            { 67, UW1GameObjectType.Monster }, //"Giant rat"},
            { 68, UW1GameObjectType.Monster }, //"Giant spider"},
            { 69, UW1GameObjectType.Monster }, //"Acid slug"},
            { 70, UW1GameObjectType.Monster }, //"Green goblin"},
            { 71, UW1GameObjectType.Monster }, //"Green goblin"},
            { 72, UW1GameObjectType.Monster }, //"Giant rat"},
            { 73, UW1GameObjectType.Monster }, //"Vampire bat"},
            { 74, UW1GameObjectType.Monster }, //"Skeleton"},
            { 75, UW1GameObjectType.Monster }, //"Imp"},
            { 76, UW1GameObjectType.Monster }, //"Grey goblin"},
            { 77, UW1GameObjectType.Monster }, //"Green goblin"},
            { 78, UW1GameObjectType.Monster }, //"Grey goblin"},
            { 79, UW1GameObjectType.Monster }, //"Ethereal Void Creatures"},
            { 80, UW1GameObjectType.Monster }, //"Grey goblin"},
            { 81, UW1GameObjectType.Monster }, //"Mongbat"},
            { 82, UW1GameObjectType.Monster }, //"Bloodworm"},
            { 83, UW1GameObjectType.Monster }, //"Wolf spider"},
            { 84, UW1GameObjectType.Monster }, //"Mountainman"},
            { 85, UW1GameObjectType.Monster }, //"Green lizardman"},
            { 86, UW1GameObjectType.Monster }, //"Mountainman"},
            { 87, UW1GameObjectType.Monster }, //"Lurker"},
            { 88, UW1GameObjectType.Monster }, //"Red lizardman"},
            { 89, UW1GameObjectType.Monster }, //"Gray lizardman"},
            { 90, UW1GameObjectType.Monster }, //"Outcast"},
            { 91, UW1GameObjectType.Monster }, //"Headless"},
            { 92, UW1GameObjectType.Monster }, //"Dread spider"},
            { 93, UW1GameObjectType.Monster }, //"Fighter"},
            { 94, UW1GameObjectType.Monster }, //"Fighter"},
            { 95, UW1GameObjectType.Monster }, //"Fighter"},
            { 96, UW1GameObjectType.Monster }, //"Troll"},
            { 97, UW1GameObjectType.Monster }, //"Ghost"},
            { 98, UW1GameObjectType.Monster }, //"Fighter"},
            { 99, UW1GameObjectType.Monster }, //"Ghoul"},
            { 100, UW1GameObjectType.Monster }, //"Ghost"},
            { 101, UW1GameObjectType.Monster }, //"Ghost"},
            { 102, UW1GameObjectType.Monster }, //"Gazer"},
            { 103, UW1GameObjectType.Monster }, //"Mage"},
            { 104, UW1GameObjectType.Monster }, //"Fighter"},
            { 105, UW1GameObjectType.Monster }, //"Dark ghoul"},
            { 106, UW1GameObjectType.Monster }, //"Mage"},
            { 107, UW1GameObjectType.Monster }, //"Mage"},
            { 108, UW1GameObjectType.Monster }, //"Mage"},
            { 109, UW1GameObjectType.Monster }, //"Mage"},
            { 110, UW1GameObjectType.Monster }, //"Ghoul"},
            { 111, UW1GameObjectType.Monster }, //"Feral troll"},
            { 112, UW1GameObjectType.Monster }, //"Great troll"},
            { 113, UW1GameObjectType.Monster }, //"Dire ghost"},
            { 114, UW1GameObjectType.Monster }, //"Earth golem"},
            { 115, UW1GameObjectType.Monster }, //"Mage"},
            { 116, UW1GameObjectType.Monster }, //"Deep lurker"},
            { 117, UW1GameObjectType.Monster }, //"Shadow beast"},
            { 118, UW1GameObjectType.Monster }, //"Reaper"},
            { 119, UW1GameObjectType.Monster }, //"Stone golem"},
            { 120, UW1GameObjectType.Monster }, //"Fire elemental"},
            { 121, UW1GameObjectType.Monster }, //"Metal golem"},
            { 122, UW1GameObjectType.Monster }, //"Wisp"},
            { 123, UW1GameObjectType.Monster }, //"Tybal"},
            { 124, UW1GameObjectType.Monster }, //"Slasher of veils"},
            { 125, UW1GameObjectType.Unknown }, //"Unknown"},
            { 126, UW1GameObjectType.Unknown }, //"Unknown"},
            { 127, UW1GameObjectType.Unknown }, //"Adventurer"},
            { 128, UW1GameObjectType.Container }, //"Sack"},
            { 129, UW1GameObjectType.Container }, //"Open sack"},
            { 130, UW1GameObjectType.Container }, //"Pack"},
            { 131, UW1GameObjectType.Container }, //"Open pack"},
            { 132, UW1GameObjectType.Container }, //"Box"},
            { 133, UW1GameObjectType.Container }, //"Open box"},
            { 134, UW1GameObjectType.Container }, //"Pouch"},
            { 135, UW1GameObjectType.Container }, //"Open pouch"},
            { 136, UW1GameObjectType.Container }, //"Map case"},
            { 137, UW1GameObjectType.Container }, //"Open map case"},
            { 138, UW1GameObjectType.Container }, //"Gold coffer"},
            { 139, UW1GameObjectType.Container }, //"Open gold coffer"},
            { 140, UW1GameObjectType.Container }, //"Urn"},
            { 141, UW1GameObjectType.Container }, //"Quiver"},
            { 142, UW1GameObjectType.Container }, //"Bowl"},
            { 143, UW1GameObjectType.Container }, //"Rune bag"},
            { 144, UW1GameObjectType.Light }, //"Lantern"},
            { 145, UW1GameObjectType.Light }, //"Torch"},
            { 146, UW1GameObjectType.Light }, //"Candle"},
            { 147, UW1GameObjectType.Light }, //"Taper"},
            { 148, UW1GameObjectType.Light }, //"Lit lantern"},
            { 149, UW1GameObjectType.Light }, //"Lit torch"},
            { 150, UW1GameObjectType.Light }, //"Lit candle"},
            { 151, UW1GameObjectType.Light }, //"Lit taper"},
            { 152, UW1GameObjectType.Wand }, //"Wand"},
            { 153, UW1GameObjectType.Wand }, //"Wand"},
            { 154, UW1GameObjectType.Wand }, //"Wand"},
            { 155, UW1GameObjectType.Wand }, //"Wand"},
            { 156, UW1GameObjectType.Countable }, //"Broken wand"},
            { 157, UW1GameObjectType.Countable }, //"Broken wand"},
            { 158, UW1GameObjectType.Countable }, //"Broken wand"},
            { 159, UW1GameObjectType.Countable }, //"Broken wand"},
            { 160, UW1GameObjectType.Gold }, //"Coin"},
            { 161, UW1GameObjectType.Gold }, //"Gold coin"},
            { 162, UW1GameObjectType.Treasure }, //"Ruby"},
            { 163, UW1GameObjectType.Treasure }, //"Red gem"},
            { 164, UW1GameObjectType.Treasure }, //"Small blue gem"},
            { 165, UW1GameObjectType.Treasure }, //"Large blue gem"},
            { 166, UW1GameObjectType.Treasure }, //"Sapphire"},
            { 167, UW1GameObjectType.Treasure }, //"Emerald"},
            { 168, UW1GameObjectType.Treasure }, //"Amulet"},
            { 169, UW1GameObjectType.Treasure }, //"Goblet"},
            { 170, UW1GameObjectType.Treasure }, //"Sceptre"},
            { 171, UW1GameObjectType.Treasure }, //"Gold chain"},
            { 172, UW1GameObjectType.Treasure }, //"Gold plate"},
            { 173, UW1GameObjectType.Treasure }, //"Ankh pendant"},
            { 174, UW1GameObjectType.Treasure }, //"Cup"},
            { 175, UW1GameObjectType.Treasure }, //"Gold nugget"},
            { 176, UW1GameObjectType.Food }, //"Meat"},
            { 177, UW1GameObjectType.Food }, //"Bread"},
            { 178, UW1GameObjectType.Food }, //"Cheese"},
            { 179, UW1GameObjectType.Food }, //"Apple"},
            { 180, UW1GameObjectType.Food }, //"Corn"},
            { 181, UW1GameObjectType.Food }, //"Bread"},
            { 182, UW1GameObjectType.Food }, //"Fish"},
            { 183, UW1GameObjectType.Food }, //"Popcorn"},
            { 184, UW1GameObjectType.Food }, //"Mushroom"},
            { 185, UW1GameObjectType.Food }, //"Toadstool"},
            { 186, UW1GameObjectType.Drink }, //"Bottle of ale"},
            { 187, UW1GameObjectType.Potion }, //"Red potion"},
            { 188, UW1GameObjectType.Potion }, //"Green potion"},
            { 189, UW1GameObjectType.Drink }, //"Bottle of water"},
            { 190, UW1GameObjectType.Drink }, //"Flask of port"},
            { 191, UW1GameObjectType.Drink }, //"Bottle of wine"},
            { 192, UW1GameObjectType.Unpickable }, //"Plant"},
            { 193, UW1GameObjectType.Unpickable }, //"Grass"},
            { 194, UW1GameObjectType.Bones }, //"Skull"},
            { 195, UW1GameObjectType.Bones }, //"Skull"},
            { 196, UW1GameObjectType.Bones }, //"Bone"},
            { 197, UW1GameObjectType.Bones }, //"Bone"},
            { 198, UW1GameObjectType.Bones }, //"Pile of bones"},
            { 199, UW1GameObjectType.Unpickable }, //"Vines"},
            { 200, UW1GameObjectType.Countable }, //"Broken axe"},
            { 201, UW1GameObjectType.Countable }, //"Broken sword"},
            { 202, UW1GameObjectType.Countable }, //"Broken mace"},
            { 203, UW1GameObjectType.Countable }, //"Broken shield"},
            { 204, UW1GameObjectType.Countable }, //"Piece of wood"},
            { 205, UW1GameObjectType.Countable }, //"Piece of wood"},
            { 206, UW1GameObjectType.Countable }, //"Plant"},
            { 207, UW1GameObjectType.Countable }, //"Plant"},
            { 208, UW1GameObjectType.Unpickable }, //"Pile of debris"},
            { 209, UW1GameObjectType.Unpickable }, // "Pile of debris"},
            { 210, UW1GameObjectType.Unpickable }, // "Pile of debris"},
            { 211, UW1GameObjectType.CeilingHugger }, // "Stalactite"},
            { 212, UW1GameObjectType.CeilingHugger }, //"Plant"},
            { 213, UW1GameObjectType.Unpickable }, // "Pile of debris"},
            { 214, UW1GameObjectType.Unpickable }, // "Pile of debris"},
            { 215, UW1GameObjectType.Unpickable }, // "Anvil"},
            { 216, UW1GameObjectType.Countable }, //"Pole"},
            { 217, UW1GameObjectType.Countable }, //"Dead rotworm"},
            { 218, UW1GameObjectType.Unpickable }, //"Rubble"},
            { 219, UW1GameObjectType.Unpickable }, //"Pile of wood chips"},
            { 220, UW1GameObjectType.Unpickable }, //"Pile of bones"},
            { 221, UW1GameObjectType.Unpickable }, //"Blood stain"},
            { 222, UW1GameObjectType.Unpickable }, //"Blood stain"},
            { 223, UW1GameObjectType.Unpickable }, //"Blood stain"},
            { 224, UW1GameObjectType.Unknown }, //"Runestone"},
            { 225, UW1GameObjectType.Uncountable }, //"The key of truth"},
            { 226, UW1GameObjectType.Uncountable }, //"The key of love"},
            { 227, UW1GameObjectType.Uncountable }, //"The key of courage"},
            { 228, UW1GameObjectType.Uncountable }, //"Two part key"},
            { 229, UW1GameObjectType.Uncountable }, //"Two part key"},
            { 230, UW1GameObjectType.Uncountable }, //"Two part key"},
            { 231, UW1GameObjectType.Uncountable }, //"Key of infinity"},
            { 232, UW1GameObjectType.Runestone }, //"An rune"},
            { 233, UW1GameObjectType.Runestone }, //"Bet rune"},
            { 234, UW1GameObjectType.Runestone }, //"Corp rune"},
            { 235, UW1GameObjectType.Runestone }, //"Des rune"},
            { 236, UW1GameObjectType.Runestone }, //"Ex rune"},
            { 237, UW1GameObjectType.Runestone }, //"Flam rune"},
            { 238, UW1GameObjectType.Runestone }, //"Grav rune"},
            { 239, UW1GameObjectType.Runestone }, //"Hur rune"},
            { 240, UW1GameObjectType.Runestone }, //"In rune"},
            { 241, UW1GameObjectType.Runestone }, //"Jux rune"},
            { 242, UW1GameObjectType.Runestone }, //"Kal rune"},
            { 243, UW1GameObjectType.Runestone }, //"Lor rune"},
            { 244, UW1GameObjectType.Runestone }, //"Mani rune"},
            { 245, UW1GameObjectType.Runestone }, //"Nox rune"},
            { 246, UW1GameObjectType.Runestone }, //"Ort rune"},
            { 247, UW1GameObjectType.Runestone }, //"Por rune"},
            { 248, UW1GameObjectType.Runestone }, //"Quas rune"},
            { 249, UW1GameObjectType.Runestone }, //"Rel rune"},
            { 250, UW1GameObjectType.Runestone }, //"Sanct rune"},
            { 251, UW1GameObjectType.Runestone }, //"Tym rune"},
            { 252, UW1GameObjectType.Runestone }, //"Uus rune"},
            { 253, UW1GameObjectType.Runestone }, //"Vas rune"},
            { 254, UW1GameObjectType.Runestone }, //"Wis rune"},
            { 255, UW1GameObjectType.Runestone }, //"Ylem rune"},
            { 256, UW1GameObjectType.Key }, //"Key"},
            { 257, UW1GameObjectType.Countable }, //"Lockpick"},
            { 258, UW1GameObjectType.Runestone }, //"Key"},
            { 259, UW1GameObjectType.Key }, //"Key"},
            { 260, UW1GameObjectType.Key }, //"Key"},
            { 261, UW1GameObjectType.Key }, //"Key"},
            { 262, UW1GameObjectType.Key }, //"Key"},
            { 263, UW1GameObjectType.Key }, //"Key"},
            { 264, UW1GameObjectType.Key }, //"Key"},
            { 265, UW1GameObjectType.Key }, //"Key"},
            { 266, UW1GameObjectType.Key }, //"Key"},
            { 267, UW1GameObjectType.Key }, //"Key"},
            { 268, UW1GameObjectType.Key }, //"Key"},
            { 269, UW1GameObjectType.Key }, //"Key"},
            { 270, UW1GameObjectType.Key }, //"Key"},
            { 271, UW1GameObjectType.Lock }, //"Lock"},
            { 272, UW1GameObjectType.Uncountable }, //"Picture of tom"},
            { 273, UW1GameObjectType.Uncountable }, //"Crystal splinter"},
            { 274, UW1GameObjectType.Countable }, //"Orb rock"},
            { 275, UW1GameObjectType.Uncountable }, //"The gem cutter of coulnes"},
            { 276, UW1GameObjectType.Uncountable }, //"Exploding book"},
            { 277, UW1GameObjectType.Countable }, //"Block of burning incense"},
            { 278, UW1GameObjectType.Countable }, //"Block of incense"},
            { 279, UW1GameObjectType.Unpickable }, //"Orb"},
            { 280, UW1GameObjectType.Uncountable }, //"Broken blade"},
            { 281, UW1GameObjectType.Uncountable }, //"Broken hilt"},
            { 282, UW1GameObjectType.Uncountable }, //"Figurine"},
            { 283, UW1GameObjectType.Uncountable }, //"Rotworm stew"},
            { 284, UW1GameObjectType.Countable }, //"Strong thread"},
            { 285, UW1GameObjectType.Uncountable }, //"Dragon scales"},
            { 286, UW1GameObjectType.Countable }, //"Resilient sphere"},
            { 287, UW1GameObjectType.Uncountable }, //"Standard"},
            { 288, UW1GameObjectType.Spell }, //"Spell"},
            { 289, UW1GameObjectType.Countable }, //"Bedroll"},
            { 290, UW1GameObjectType.Uncountable }, //"Silver seed"},
            { 291, UW1GameObjectType.Countable }, //"Mandolin"},
            { 292, UW1GameObjectType.Countable }, //"Flute"},
            { 293, UW1GameObjectType.Countable }, //"Leeches"},
            { 294, UW1GameObjectType.Uncountable }, //"Moonstone"},
            { 295, UW1GameObjectType.Countable }, //"Spike"},
            { 296, UW1GameObjectType.Countable }, //"Rock hammer"},
            { 297, UW1GameObjectType.Countable }, //"Glowing rock"},
            { 298, UW1GameObjectType.Unpickable }, //"Campfire"},
            { 299, UW1GameObjectType.Countable }, //"Fishing pole"},
            { 300, UW1GameObjectType.Countable }, //"Medallion"},
            { 301, UW1GameObjectType.Countable }, //"Oil flask"},
            { 302, UW1GameObjectType.Unpickable }, //"Fountain"},
            { 303, UW1GameObjectType.Unpickable }, //"Cauldron"},
            { 304, UW1GameObjectType.Book }, //"Book"},
            { 305, UW1GameObjectType.Book }, //"Book"},
            { 306, UW1GameObjectType.Book }, //"Book"},
            { 307, UW1GameObjectType.Book }, //"Book"},
            { 308, UW1GameObjectType.Book }, //"Book"},
            { 309, UW1GameObjectType.Book }, //"Book"},
            { 310, UW1GameObjectType.Book }, //"Book"},
            { 311, UW1GameObjectType.Book }, //"Book"},
            { 312, UW1GameObjectType.Scroll }, //"Scroll"},
            { 313, UW1GameObjectType.Scroll }, //"Scroll"},
            { 314, UW1GameObjectType.Scroll }, //"Scroll"},
            { 315, UW1GameObjectType.Map }, //"Map"},
            { 316, UW1GameObjectType.Scroll }, //"Scroll"},
            { 317, UW1GameObjectType.Scroll }, //"Scroll"},
            { 318, UW1GameObjectType.Scroll }, //"Scroll"},
            { 319, UW1GameObjectType.Scroll }, //"Scroll"},
            { 320, UW1GameObjectType.Door }, //"Door"},
            { 321, UW1GameObjectType.Door }, //"Door"},
            { 322, UW1GameObjectType.Door }, //"Door"},
            { 323, UW1GameObjectType.Door }, //"Door"},
            { 324, UW1GameObjectType.Door }, //"Door"},
            { 325, UW1GameObjectType.Door }, //"Door"},
            { 326, UW1GameObjectType.Door }, //"Portcullis"},
            { 327, UW1GameObjectType.Door }, //"Secret door"},
            { 328, UW1GameObjectType.Door }, //"Open door"},
            { 329, UW1GameObjectType.Door }, //"Open door"},
            { 330, UW1GameObjectType.Door }, //"Open door"},
            { 331, UW1GameObjectType.Door }, //"Open door"},
            { 332, UW1GameObjectType.Door }, //"Open door"},
            { 333, UW1GameObjectType.Door }, //"Open door"},
            { 334, UW1GameObjectType.Door }, //"Open portcullis"},
            { 335, UW1GameObjectType.Door }, //"Secret door"},
            { 336, UW1GameObjectType.Model }, //"Bench"},
            { 337, UW1GameObjectType.Model }, //"Arrow"},
            { 338, UW1GameObjectType.Model }, //"Crossbow bolt"},
            { 339, UW1GameObjectType.Model }, //"Large boulder"},
            { 340, UW1GameObjectType.Model }, //"Large boulder"},
            { 341, UW1GameObjectType.Model }, //"Boulder"},
            { 342, UW1GameObjectType.Model }, //"Small boulder"},
            { 343, UW1GameObjectType.Model }, //"Shrine"},
            { 344, UW1GameObjectType.Model }, //"Table"},
            { 345, UW1GameObjectType.Model }, //"Beam"},
            { 346, UW1GameObjectType.Model }, //"Moongate"},
            { 347, UW1GameObjectType.ContainerModel }, //"Barrel"},
            { 348, UW1GameObjectType.Model }, //"Chair"},
            { 349, UW1GameObjectType.ContainerModel }, //"Chest"},
            { 350, UW1GameObjectType.Model }, //"Nightstand"},
            { 351, UW1GameObjectType.Model }, //"Lotus turbo esprit"},
            { 352, UW1GameObjectType.Model }, //"Pillar"},
            { 353, UW1GameObjectType.DialLever }, //"Lever"},
            { 354, UW1GameObjectType.DialLever }, //"Switch"},
            { 355, UW1GameObjectType.Model }, //"Unknown"},
            { 356, UW1GameObjectType.Model }, //"Bridge"},
            { 357, UW1GameObjectType.Grave }, //"Gravestone"},
            { 358, UW1GameObjectType.Writing }, //"Writing"},
            { 359, UW1GameObjectType.Unknown }, //"Unknown"},
            { 360, UW1GameObjectType.Unknown }, //"Unknown"},
            { 361, UW1GameObjectType.Unknown }, //"Unknown"},
            { 362, UW1GameObjectType.Unknown }, //"Unknown"},
            { 363, UW1GameObjectType.Unknown }, //"Unknown"},
            { 364, UW1GameObjectType.Unknown }, //"Unknown"},
            { 365, UW1GameObjectType.Unknown }, //"Force field"},
            { 366, UW1GameObjectType.VerticalTexture }, //"Vertical texture"},
            { 367, UW1GameObjectType.VerticalTexture }, //"Special tmap obj"},
            { 368, UW1GameObjectType.Lever }, //"Button"},
            { 369, UW1GameObjectType.Lever }, //"Button"},
            { 370, UW1GameObjectType.Lever }, //"Button"},
            { 371, UW1GameObjectType.Lever }, //"Switch"},
            { 372, UW1GameObjectType.Lever }, //"Switch"},
            { 373, UW1GameObjectType.Lever }, //"Lever"},
            { 374, UW1GameObjectType.Lever }, //"Pull chain"},
            { 375, UW1GameObjectType.Lever }, //"Pull chain"},
            { 376, UW1GameObjectType.Lever }, //"Button"},
            { 377, UW1GameObjectType.Lever }, //"Button"},
            { 378, UW1GameObjectType.Lever }, //"Button"},
            { 379, UW1GameObjectType.Lever }, //"Switch"},
            { 380, UW1GameObjectType.Lever }, //"Switch"},
            { 381, UW1GameObjectType.Lever }, //"Lever"},
            { 382, UW1GameObjectType.Lever }, //"Pull chain"},
            { 383, UW1GameObjectType.Lever }, //"Pull chain"},
            { 384, UW1GameObjectType.Trap }, //"Damage trap"},
            { 385, UW1GameObjectType.Trap }, //"Teleport trap"},
            { 386, UW1GameObjectType.Trap }, //"Arrow trap"},
            { 387, UW1GameObjectType.Unknown }, //"Do trap"},
            { 388, UW1GameObjectType.Trap }, //"Pit trap"},
            { 389, UW1GameObjectType.Trap }, //"Change terrain trap"},
            { 390, UW1GameObjectType.Trap }, //"Spelltrap"},
            { 391, UW1GameObjectType.Trap }, //"Create object trap"},
            { 392, UW1GameObjectType.DoorTrap }, //"Door trap"},
            { 393, UW1GameObjectType.Unknown }, //"Ward trap"},
            { 394, UW1GameObjectType.Unknown }, //"Tell trap"},
            { 395, UW1GameObjectType.Trap }, //"Delete object trap"},
            { 396, UW1GameObjectType.Trap }, //"Inventory trap"},
            { 397, UW1GameObjectType.Trap }, //"Set variable trap"},
            { 398, UW1GameObjectType.Trap }, //"Check variable trap"},
            { 399, UW1GameObjectType.Unknown }, //"Combination trap"},
            { 400, UW1GameObjectType.Trap }, //"Text string trap"},
            { 401, UW1GameObjectType.Unknown }, //"Unknown"},
            { 402, UW1GameObjectType.Unknown }, //"Unknown"},
            { 403, UW1GameObjectType.Unknown }, //"Unknown"},
            { 404, UW1GameObjectType.Unknown }, //"Unknown"},
            { 405, UW1GameObjectType.Unknown }, //"Unknown"},
            { 406, UW1GameObjectType.Unknown }, //"Unknown"},
            { 407, UW1GameObjectType.Unknown }, //"Unknown"},
            { 408, UW1GameObjectType.Unknown }, //"Unknown"},
            { 409, UW1GameObjectType.Unknown }, //"Unknown"},
            { 410, UW1GameObjectType.Unknown }, //"Unknown"},
            { 411, UW1GameObjectType.Unknown }, //"Unknown"},
            { 412, UW1GameObjectType.Unknown }, //"Unknown"},
            { 413, UW1GameObjectType.Unknown }, //"Unknown"},
            { 414, UW1GameObjectType.Unknown }, //"Unknown"},
            { 415, UW1GameObjectType.Unknown }, //"Unknown"},
            { 416, UW1GameObjectType.Trigger }, //"Move trigger"},
            { 417, UW1GameObjectType.Trigger }, //"Pick up trigger"},
            { 418, UW1GameObjectType.Trigger }, //"Use trigger"},
            { 419, UW1GameObjectType.Trigger }, //"Look trigger"},
            { 420, UW1GameObjectType.Unknown }, //"Step on trigger"},
            { 421, UW1GameObjectType.Trigger }, //"Open trigger"},
            { 422, UW1GameObjectType.Trigger }, //"Unlock trigger"},
            { 423, UW1GameObjectType.Unknown }, //"Unknown"},
            { 424, UW1GameObjectType.Unknown }, //"Unknown"},
            { 425, UW1GameObjectType.Unknown }, //"Unknown"},
            { 426, UW1GameObjectType.Unknown }, //"Unknown"},
            { 427, UW1GameObjectType.Unknown }, //"Unknown"},
            { 428, UW1GameObjectType.Unknown }, //"Unknown"},
            { 429, UW1GameObjectType.Unknown }, //"Unknown"},
            { 430, UW1GameObjectType.Unknown }, //"Unknown"},
            { 431, UW1GameObjectType.Unknown }, //"Unknown"},
            { 432, UW1GameObjectType.Unknown }, //"Unknown"},
            { 433, UW1GameObjectType.Unknown }, //"Unknown"},
            { 434, UW1GameObjectType.Unknown }, //"Unknown"},
            { 435, UW1GameObjectType.Unknown }, //"Unknown"},
            { 436, UW1GameObjectType.Unknown }, //"Unknown"},
            { 437, UW1GameObjectType.Unknown }, //"Unknown"},
            { 438, UW1GameObjectType.Unknown }, //"Unknown"},
            { 439, UW1GameObjectType.Unknown }, //"Unknown"},
            { 440, UW1GameObjectType.Unknown }, //"Unknown"},
            { 441, UW1GameObjectType.Unknown }, //"Unknown"},
            { 442, UW1GameObjectType.Unknown }, //"Unknown"},
            { 443, UW1GameObjectType.Unknown }, //"Unknown"},
            { 444, UW1GameObjectType.Unknown }, //"Unknown"},
            { 445, UW1GameObjectType.Unknown }, //"Unknown"},
            { 446, UW1GameObjectType.Unknown }, //"Unknown"},
            { 447, UW1GameObjectType.Unknown }, //"Unknown"},
            { 448, UW1GameObjectType.Animated }, //"Some blood"},
            { 449, UW1GameObjectType.Animated }, //"A mist cloud"},
            { 450, UW1GameObjectType.Animated }, //"An explosion"},
            { 451, UW1GameObjectType.Animated }, //"An explosion"},
            { 452, UW1GameObjectType.Animated }, //"An explosion"},
            { 453, UW1GameObjectType.Animated }, //"A splash"},
            { 454, UW1GameObjectType.Animated }, //"A splash"},
            { 455, UW1GameObjectType.Animated }, //"A spell effect"},
            { 456, UW1GameObjectType.Animated }, //"Some smoke"},
            { 457, UW1GameObjectType.Animated }, //"Fountain"},
            { 458, UW1GameObjectType.Animated }, //"Silver tree"},
            { 459, UW1GameObjectType.Animated }, //"Some damage"},
            { 460, UW1GameObjectType.Unknown }, //"Unknown"},
            { 461, UW1GameObjectType.Unknown }, //"A sound source"},
            { 462, UW1GameObjectType.Unknown }, //"Some changing terrain"},
            { 463, UW1GameObjectType.Unknown }, //"A moving door"},
            { 464, UW1GameObjectType.Unknown }, //"Outofrange"},
            { 465, UW1GameObjectType.Trap }, // "Attitude trap"},//465 : attitude trap
            { 466, UW1GameObjectType.Trap }, // "Platform trap"},//466 : platform trap
            { 467, UW1GameObjectType.Trap }, // "Camera trap"},//467 : camera trap
            { 468, UW1GameObjectType.Trap }, // "Conversation trap"},//468 : conv trap
            { 469, UW1GameObjectType.Trap }, // "End game trap"},//469 : end game trap
            { default, UW1GameObjectType.Unknown },
        };


    public enum UW1ObjectNames : ushort
    {
        HandAxe,
        BattleAxe,
        Axe,
        Dagger,
        Shortsword,
        Longsword,
        Broadsword,
        Cudgel,
        LightMace,
        Mace,
        ShinySword,
        JeweledAxe,
        BlackSword,
        JeweledSword,
        JeweledMace,
        Fist,
        SlingStone_Item,
        CrossbowBolt_Item,
        ArrowItem,
        Stone,
        Fireball,
        LightningBolt,
        Acid,
        MagicMissile,
        Sling,
        Bow,
        Crossbow,
        Unknown1,
        Unknown2,
        Unknown3,
        Unknown4,
        JeweledBow,
        LeatherVest,
        MailShirt,
        Breastplate,
        LeatherLeggings,
        MailLeggings,
        PlateLeggings,
        LeatherGloves,
        ChainGauntlets,
        PlateGauntlets,
        LeatherBoots,
        ChainBoots,
        PlateBoots,
        LeatherCap,
        ChainCowl,
        Helmet,
        DragonSkinBoots,
        Crown1,
        Crown2,
        Crown3,
        Unknown5,
        Unknown6,
        Unknown7,
        IronRing,
        ShinyShield_Artifact,
        GoldRing,
        SilverRing,
        RedRing,
        TowerShield,
        WoodenShield,
        SmallShield,
        Buckler,
        JeweledShield,
        Rotworm,
        FleshSlug,
        CaveBat,
        GiantRat,
        GiantSpider,
        AcidSlug,
        GreenGoblin1,
        GreenGoblin2,
        GiantRat2,
        VampireBat,
        Skeleton,
        Imp,
        GreyGoblin2,
        GreenGoblin3,
        GreyGoblin3,
        EtherealVoidCreatures,
        GreyGoblin4,
        Mongbat,
        Bloodworm,
        WolfSpider,
        Mountainman1,
        GreenLizardman,
        Mountainman2,
        Lurker,
        RedLizardman,
        GrayLizardman,
        Outcast,
        Headless,
        DreadSpider,
        Fighter1,
        Fighter2,
        Fighter3,
        Troll,
        Ghost1,
        Fighter4,
        Ghoul,
        Ghost2,
        Ghost3,
        Gazer,
        Mage1,
        Fighter,
        DarkGhoul,
        Mage2,
        Mage3,
        Mage4,
        Mage5,
        FeralGhoul,
        FeralTroll,
        GreatTroll,
        DireGhost,
        EarthGolem,
        Mage6,
        DeepLurker,
        ShadowBeast,
        Reaper,
        StoneGolem,
        FireElemental,
        MetalGolem,
        Wisp,
        Tybal,
        SlasherOfVeils,
        Unknown8,
        Unknown9,
        Adventurer,
        Sack,
        SackOpen,
        Pack,
        PackOpen,
        Box,
        BoxOpen,
        Pouch,
        PouchOpen,
        MapCase,
        MapCaseOpen,
        GoldCoffer,
        GoldCofferOpen,
        Urn,
        Quiver,
        Bowl,
        RuneBag,
        Lantern,
        Torch,
        Candle,
        Taper_Artifact,
        LanternLit,
        TorchLit,
        CandleLit,
        TaperLit,
        Wand1,
        Wand2,
        Wand3,
        Wand4,
        BrokenWand1,
        BrokenWand2,
        BrokenWand3,
        BrokenWand4,
        Coin,
        GoldCoin,
        Ruby,
        RedGem,
        SmallBlueGem,
        LargeBlueGem,
        Sapphire,
        Emerald,
        Amulet,
        Goblet,
        Sceptre,
        GoldChain,
        GoldPlate,
        AnkhPendant,
        Cup_Artifact,
        GoldNugget,
        Meat,
        Bread1,
        Cheese,
        Apple,
        Corn,
        Bread2,
        Fish,
        Popcorn,
        Mushroom,
        Toadstool,
        BottleOfAle,
        RedPotion,
        GreenPotion,
        BottleOfWater,
        FlaskOfPort,
        BottleOfWine,
        Plant1,
        Grass,
        Skull1,
        Skull2,
        Bone1,
        Bone2,
        PileOfBones1,
        Vines,
        BrokenAxe,
        BrokenSword,
        BrokenMace,
        BrokenShield,
        PieceOfWood1,
        PieceOfWood2,
        Plant2,
        Plant3,
        PileOfDebris1,
        PileOfDebris2,
        PileOfDebris3,
        Stalactite,
        Plant4,
        PileOfDebris4,
        PileOfDebris5,
        Anvil,
        Pole,
        RotwormDead,
        Rubble,
        PileOfWoodChips,
        PileOfBones,
        BloodStain1,
        BloodStain2,
        BloodStain3,
        Runestone_Unk,
        TheKeyOfTruth,
        TheKeyOfLove,
        TheKeyOfCourage,
        TwoPartKey_TC,
        TwoPartKey_LC,
        TwoPartKey_TL,
        KeyOfInfinity,
        AnRune,
        BetRune,
        Corp_rune,
        Des_rune,
        Ex_rune,
        Flam_rune,
        Grav_rune,
        Hur_rune,
        In_rune,
        Jux_rune,
        Kal_rune,
        Lor_rune,
        Mani_rune,
        Nox_rune,
        Ort_rune,
        Por_rune,
        Quas_rune,
        Rel_rune,
        Sanct_rune,
        Tym_rune,
        Uus_rune,
        Vas_rune,
        Wis_rune,
        Ylem_rune,
        Key_GoldSmall,
        Lockpick,
        Key_SilverHeart,
        Key_BrownRedGem,
        Key_GreySkull,
        Key_YellowHeart,
        Key_Red,
        Key_BrownGreenGem,
        Key_GoldRedGem,
        Key_SilverRedGem,
        Key_Silver,
        Key_SilverGoldGem,
        Key_BrownHeart,
        Key_Gray,
        Key_BoneSkull,
        Lock,
        PictureOfTom,
        CrystalSplinter,
        OrbRock,
        TheGemCutterOfCoulnes,
        ExplodingBook,
        BlockOfBurningIncense,
        BlockOfIncense,
        Orb,
        BrokenBlade,
        BrokenHilt,
        Figurine,
        RotwormStew,
        StrongThread,
        DragonScales,
        ResilientSphere,
        Standard,
        Spell,
        Bedroll,
        SilverSeed,
        Mandolin,
        Flute,
        Leeches,
        Moonstone,
        Spike,
        RockHammer,
        GlowingRock,
        Campfire,
        FishingPole,
        Medallion,
        OilFlask,
        Fountain1,
        Cauldron,
        Book_Skull,
        Book_Rings,
        Book_BlankCover,
        Book_DarkRedWriting,
        Book_Star,
        Book_Brown,
        Book_SmallRedStar,
        Book_Black,
        Scroll_Diagonal,
        Scroll_ClosedHorizontal,
        Scroll_OpenSmallHorizontal,
        Map,
        Scroll_BrownSquare,
        Scroll_SilverSquare,
        Scroll_SquareDiagonal,
        Scroll_SilverDiagonal,
        DoorWooden1,
        Door_Wooden2,
        Door_Wooden3,
        Door_Wooden4,
        Door_Wooden5,
        MassiveDoor,
        Portcullis,
        SecretDoor1,
        OpenDoor1,
        OpenDoor2,
        OpenDoor3,
        OpenDoor4,
        OpenDoor5,
        OpenMassiveDoor,
        OpenPortcullis,
        OpenSecretDoor,
        Bench,
        Arrow_3D,
        CrossbowBolt_3D,
        LargeBoulder1,
        LargeBoulder2,
        Boulder,
        SmallBoulder,
        Shrine,
        Table,
        Beam,
        Moongate,
        Barrel,
        Chair,
        Chest,
        Nightstand,
        LotusTurboEsprit,
        Pillar,
        DialLeverClock,
        DialLeverPoints,
        Unknown10,
        Bridge,
        Grave,
        Writing,
        Unknown11,
        Unknown12,
        Unknown13,
        Unknown14,
        Unknown15,
        Unknown16,
        Unknown17,
        PassableWall,
        ImpassableWall,
        Button_SilverOn,
        Button_BronzeSilverCenterOn,
        Button_BronzeBronzeCenterOn,
        Switch_SilverUp,
        Switch_BronzeUp,
        Lever_Down,
        PullChain_LongUp,
        PullChain_ShortUp,
        Button_SilverOff,
        Button_BronzeSilverCenterOff,
        Button_BronzeBronzeCenterOff,
        Switch_SilverDown,
        Switch_BronzeDown,
        Lever_Up,
        PullChain_LongDown,
        PullChain_ShortDown,
        DamageTrap,
        TeleportTrap,
        ArrowTrap,
        DoTrap,
        PitTrap,
        ChangeTerrainTrap,
        SpellTrap,
        CreateObjectTrap,
        DoorTrap,
        WardTrap,
        TellTrap,
        DeleteObjectTrap,
        InventoryTrap,
        SetVariableTrap,
        CheckVariableTrap,
        CombinationTrap,
        TextStringTrap,
        Unknown18,
        Unknown19,
        Unknown20,
        Unknown21,
        Unknown22,
        Unknown23,
        Unknown24,
        Unknown25,
        Unknown26,
        Unknown27,
        Unknown28,
        Unknown29,
        Unknown30,
        Unknown31,
        MoveTrigger,
        PickUpTrigger,
        UseTrigger,
        LookTrigger,
        StepOnTrigger,
        OpenTrigger,
        UnlockTrigger,
        Unknown32,
        Unknown33,
        Unknown34,
        Unknown35,
        Unknown36,
        Unknown37,
        Unknown38,
        Unknown39,
        Unknown40,
        Unknown41,
        Unknown42,
        Unknown43,
        Unknown44,
        Unknown45,
        Unknown46,
        Unknown47,
        Unknown48,
        Unknown49,
        Unknown50,
        Unknown51,
        Unknown52,
        Unknown53,
        Unknown54,
        Unknown55,
        Unknown56,
        BloodSplatter,
        MistCloud,
        Explosion_Large,
        Explosion_Medium,
        Explosion_Small,
        Splash,
        WaterSplash,
        SpellEffect,
        Smoke,
        Fountain,
        SilverTree,
        Damage,
        Zap,
        SoundSource,
        ChangingTerrain,
        MovingDoor,
        OutOfRange,
        AttitudeTrap,
        PlatformTrap,
        CameraTrap,
        ConversationTrap,
        EndGameTrap,
    }
}