---
name: UnitTests

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest]
    name: Unit Testing
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Debug
      - name: Test 
        run: dotnet test --no-restore --verbosity normal --filter "Category!=RequiresArk&Category!=RequiresSettings"